---
version: "2.1"
services:
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.rule=Host(`whoami.home.ducnq.com`)
      - traefik.http.routers.whoami.middlewares=redirect-to-https@file
      - traefik.http.routers.whoami-secure.entrypoints=web-secure
      - traefik.http.routers.whoami-secure.rule=Host(`whoami.home.ducnq.com`)
      - traefik.http.routers.whoami-secure.tls=true
      - traefik.http.services.whoami-secure.loadbalancer.server.port=80
      
networks:
  default:
    external:
      name: tfk